typography_spectrum: 0.14978802134282887
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.6410220970865339
  lightness: 0.6629678371828049
  saturation: 0.4148791469633579
  rhythmicContrast: 0.31042058067396283
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3732712138444185
analytics:
  google: null
  facebook: null
  twitter: null
name: eldraft
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: El Draft
description: Nfl Fantasy Advice
purpose: []
