typography_spectrum: 0.7350908350199461
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4391411643009633
  lightness: 0.7646333859302104
  saturation: 0.4570215486455709
  rhythmicContrast: 0.20868778112344444
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.009297854267060757
analytics:
  google: null
  facebook: null
  twitter: null
name: eldraft
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: eldraftmx
purpose: []
